/**
 * Naming failure shapes.
 *
 * Slice 5 of docs/PLAN.md. The goal is to turn "27 runs failed" into
 * "27 failures in 6 shapes, and shape 3 is new this week".
 *
 *
 * WHY NOT EMBEDDINGS AND CLUSTERING
 *
 * The plan assumed the usual approach: embed each failure, cluster the
 * vectors, label the clusters with a model. That is the right tool for
 * free-form text, and it carries one genuinely hard problem — cluster
 * identity across runs. Today's clustering splits yesterday's shape in two,
 * or merges three into one, and every ID that referred to them stops
 * meaning anything. "Shape 3 is getting worse" becomes unanswerable.
 *
 * Compiler output is not free-form. TypeScript errors carry a code and a
 * templated message; Next's build errors follow a small number of fixed
 * forms. A signature can be extracted **deterministically** — and then the
 * signature *is* the identity. No drift, no re-matching, no relabelling,
 * and the same failure produces the same shape today and in six months.
 *
 * That trade is worth taking wherever the input has structure. Embeddings
 * remain the answer for the unstructured tail — agent refusals, prose
 * explanations — and `UNCLASSIFIED` below is deliberately the hook for it.
 *
 *
 * WHAT MAKES A GOOD SIGNATURE
 *
 * Stable across runs that fail the same way, distinct across runs that
 * fail differently. So the normaliser strips everything incidental —
 * paths, line numbers, identifier names, hashes — and keeps the shape of
 * the complaint.
 *
 *   app/page.tsx(4,7): error TS2322: Type 'string' is not assignable
 *   components/card.tsx(19,3): error TS2322: Type 'number' is not assignable
 *
 * are one shape, not two.
 */

export type FailureShape = {
  /** Stable, human-readable identity. Never a hash — these get read. */
  signature: string;
  /** Which check produced it. */
  source: "typecheck" | "bundle" | "agent";
  /** The line the signature was derived from, for spot-checking. */
  evidence: string;
};

export const UNCLASSIFIED = "unclassified";

/**
 * Type errors that mean the harness is broken, not the generated code.
 *
 * These are indistinguishable from real type errors by exit code — a
 * genuine non-zero from a genuine `tsc` diagnostic — so the
 * infrastructure-fault guard cannot catch them. The only tell is *what*
 * the error names.
 *
 * `LayoutProps` is generated by Next into `.next/types`. When the check
 * copy lacked it, every project failed typecheck including "Hello world",
 * and the baseline reported 0% across sixteen runs. Plausible, publishable,
 * entirely about a missing directory.
 *
 * Kept as a named shape rather than silently excluded: if this reappears,
 * it should be visible as a harness fault in the taxonomy rather than
 * quietly dropped from a rate.
 */
const HARNESS_TYPE_ERRORS: ReadonlyArray<{ pattern: RegExp; reason: string }> = [
  {
    pattern: /Cannot find name '(LayoutProps|PageProps|RouteContext)'/,
    reason: "Next generated types missing — run `next typegen` in the copy",
  },
];

/**
 * Strip the parts that vary between two instances of the same failure.
 *
 * Order matters: paths before line numbers, quoted strings before bare
 * numbers, or the earlier rules eat text the later ones needed.
 */
export const normalise = (line: string): string =>
  line
    .trim()
    // Absolute and relative paths, with or without a (line,col) suffix.
    .replace(/(?:\.{0,2}\/)?[\w.-]+(?:\/[\w.-]+)+\.\w+(?:\(\d+,\d+\))?/g, "<path>")
    // Bare (line,col) or :line:col.
    .replace(/\(\d+,\d+\)|:\d+:\d+/g, "<loc>")
    // Quoted identifiers and types — the part that differs case to case.
    .replace(/'[^']*'|"[^"]*"|`[^`]*`/g, "<name>")
    // Content hashes and long hex runs.
    .replace(/\b[0-9a-f]{8,}\b/gi, "<hash>")
    // Remaining standalone numbers.
    .replace(/\b\d+\b/g, "<n>")
    .replace(/\s+/g, " ")
    .trim();

/**
 * Make captured output safe to print.
 *
 * Signatures go through `normalise`, which collapses whitespace and so
 * happens to strip control characters. Evidence did not — it was built with
 * `.trim()`, which only touches the ends.
 *
 * That matters because compiler output is raw bytes from another machine.
 * On Windows every line ends `\r\n`, and a lone `\r` in the middle of a
 * printed string returns the terminal cursor to column zero: whatever comes
 * after overwrites what came before, on the same visual line.
 *
 * The symptom was `npm run shapes` appearing to drop lines — a shape's
 * number and signature simply not there, or a run count missing, with the
 * surrounding shapes intact. Nothing was dropped. The text was printed and
 * then written over, which looks identical to a printer bug and is not one.
 *
 * Reports are read by people deciding what to fix. A report that silently
 * loses a row is worse than one that fails, so evidence is now sanitised at
 * the point it is captured rather than at the point it is displayed.
 */
export const sanitize = (text: string): string =>
  text
    // Control characters except none — including \r, \n, \t, and the ANSI
    // escape introducer, which compilers emit for colour.
    // eslint-disable-next-line no-control-regex
    .replace(/[\u0000-\u001F\u007F]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();

/** TypeScript diagnostics: `error TS2322: Type 'x' is not assignable…` */
const typescriptShape = (text: string): FailureShape | null => {
  const match = text.match(/error (TS\d+):\s*([^\n]+)/);
  if (!match) return null;

  const [, code, message] = match;

  // Named explicitly so a broken harness reads as a broken harness rather
  // than as a fleet of bad generations.
  const harness = HARNESS_TYPE_ERRORS.find(({ pattern }) => pattern.test(text));
  if (harness) {
    return {
      signature: `HARNESS: ${harness.reason}`,
      source: "typecheck",
      evidence: sanitize(match[0]),
    };
  }

  return {
    signature: `${code}: ${normalise(message)}`,
    source: "typecheck",
    evidence: sanitize(match[0]),
  };
};

/**
 * Next build failures, in the handful of forms it actually emits.
 *
 * Ordered most specific first. `Module not found` and `Failed to compile`
 * often appear in the same output, and the first is the useful one.
 */
const NEXT_PATTERNS: ReadonlyArray<{
  pattern: RegExp;
  label: string;
  /** Capture group holding an identifier that must be redacted. */
  redact?: number;
}> = [
  { pattern: /Module not found:\s*([^\n]+)/, label: "Module not found" },
  /**
   * The code compiled and then threw while rendering.
   *
   * Next prerenders static pages during `next build`, so a component that
   * crashes on render fails the build without a single compile error. The
   * output says `✓ Compiled successfully` a few lines above.
   *
   * This is the most interesting failure class the harness sees, and it sat
   * in `unclassified` until someone read it — which is the bucket working
   * as designed rather than failing. The generic `Error:` patterns below
   * did not catch it: they require `use client`, and this one is a context
   * used outside its provider.
   *
   * Worth its own shape because it is the only category where typecheck
   * passes, the bundle compiles, and the app is still broken. Folding it
   * into a build failure would lose exactly the distinction that makes it
   * worth knowing about.
   *
   * Captures the thrown error rather than the page: the page name varies
   * per generation and the error is the cause. Not redacted, unlike the
   * export-not-found pattern — two different thrown errors really are two
   * different bugs, where two missing exports from one package are one.
   */
  {
    pattern: /Error occurred prerendering page[\s\S]*?\nError: ([^\n]+)/,
    label: "Prerender error",
  },
  { pattern: /(You're importing a component that needs[^\n]+)/, label: "Server/client boundary" },
  { pattern: /(Error: .*?use client[^\n]*)/, label: "Server/client boundary" },
  { pattern: /(ReferenceError: [^\n]+)/, label: "ReferenceError" },
  { pattern: /(SyntaxError: [^\n]+)/, label: "SyntaxError" },
  { pattern: /(TypeError: [^\n]+)/, label: "TypeError" },
  { pattern: /Export .* doesn't exist in target module/, label: "Bad export" },
  /**
   * Turbopack's current phrasing for the same thing. The older message above
   * no longer matches what Next 16 emits, so without this line the failure
   * falls through to `Cannot find module` — or past it, into unclassified.
   *
   * KEPT SEPARATE FROM `Cannot find module` ON PURPOSE. They look alike and
   * mean opposite things:
   *
   *   - module not found  → the package is absent. Usually the template.
   *   - export not found  → the package is present and the name is not in
   *     it. Either the agent invented a name, or the installed version
   *     dropped one that used to exist.
   *
   * Collapsing them would send every investigation to the wrong place.
   */
  {
    pattern: /The export (\S+) was not found in module/,
    label: "Export not found",
    /**
     * The exported name is bare — not quoted — so `normalise` leaves it
     * alone, and the signature would carry the identifier. `Github` and
     * `Linkedin` would then be two shapes for one cause, and a tally
     * fragments into instances rather than grouping them.
     *
     * The TS2305 form of this same failure collapses correctly because tsc
     * quotes the identifier. This one has to be told.
     */
    redact: 1,
  },
  { pattern: /(Cannot find module [^\n]+)/, label: "Cannot find module" },
];

const bundleShape = (text: string): FailureShape | null => {
  for (const { pattern, label, redact } of NEXT_PATTERNS) {
    const match = text.match(pattern);
    if (!match) continue;

    // Redact inside the full match rather than using the captured group:
    // the surrounding words are what make the signature readable, and the
    // group is the only part that varies.
    const detail =
      redact !== undefined && match[redact]
        ? match[0].replace(match[redact], "<name>")
        : (match[1] ?? match[0]);

    return {
      signature: `${label}: ${normalise(detail)}`,
      source: "bundle",
      evidence: sanitize(match[0]).slice(0, 300),
    };
  }
  return null;
};

/**
 * Model-provider rejections.
 *
 * Deliberately classified as agent failures, not infrastructure faults.
 *
 * A 429 is throttling and says nothing about the run. A 400 is different:
 * the request was malformed or too large, and the most likely cause is the
 * agent looping until it exhausted the context window. That is a real
 * failure mode of the agent, and burying it in the infrastructure bucket
 * would hide it.
 *
 * Observed concentrated in the adversarial tier — four of five cases —
 * which is exactly where an agent flailing against an impossible request
 * would blow its context.
 */
const providerShape = (text: string): FailureShape | null => {
  if (/context.{0,20}(length|window)|too many tokens|maximum context/i.test(text)) {
    return {
      signature: "Provider rejected: context exhausted",
      source: "agent",
      evidence: sanitize(text).slice(0, 300),
    };
  }

  const status = text.match(/unsuccessful status code:?\s*(\d{3})/i)?.[1];
  if (status && status.startsWith("4")) {
    return {
      // Kept distinct from the context case: same symptom, different cause,
      // and merging them would make the common one invisible.
      signature: `Provider rejected request (${status})`,
      source: "agent",
      evidence: sanitize(text).slice(0, 300),
    };
  }

  if (/AIGatewayError|AI request failed/i.test(text)) {
    return {
      signature: "Provider request failed",
      source: "agent",
      evidence: sanitize(text).slice(0, 300),
    };
  }

  return null;
};

/** Agent failures: produced nothing, or said why it could not. */
const agentShape = (text: string): FailureShape | null => {
  /**
   * A refusal is not a failure to produce.
   *
   * `adversarial-01` is a prompt-injection attempt. A run of it ended with
   * the agent declining, explaining that it would not reveal its
   * instructions, and asking what the user actually wanted built. No files,
   * no summary — so the harness scored it "Agent produced no summary" and
   * counted it among the agent's failures.
   *
   * That is backwards. The case exists to check the agent refuses, the
   * agent refused, and the measurement recorded the correct behaviour as a
   * defect. Exactly the substitution this project exists to catch, found in
   * the project's own taxonomy.
   *
   * Given its own shape rather than folded into the failures. It is still
   * not scored as a pass — whether a refusal counts as success is a
   * judgement about the golden set, and a taxonomy should describe what
   * happened and leave the scoring to something that says it is scoring.
   * Naming it is what makes the question askable at all.
   *
   * Matched on refusal language near the end of the agent's last message.
   * Imperfect: a generated app *about* AI assistants could trip it. The
   * alternative is leaving correct behaviour recorded as a fault, and a
   * shape that is occasionally wrong is easier to notice than a silent
   * miscount.
   */
  const REFUSAL =
    /\b(I (?:can(?:not|'t)|won't|will not|am not able to)|I'm not going to|I need to decline|I have to decline)\b|ignore (?:my|the|previous) instructions|system prompt/i;

  if (/summary: false/.test(text) && REFUSAL.test(text)) {
    return {
      signature: "Agent declined the request",
      source: "agent",
      evidence: sanitize(text).slice(-300),
    };
  }

  if (/summary: false/.test(text)) {
    return {
      signature: "Agent produced no summary",
      source: "agent",
      evidence: "no <task_summary> emitted",
    };
  }

  if (/files: 0/.test(text)) {
    return {
      signature: "Agent wrote no files",
      source: "agent",
      evidence: "fileCount 0",
    };
  }

  return null;
};

/**
 * Derive the shape of a failure.
 *
 * Returns UNCLASSIFIED rather than guessing. A bucket that absorbs
 * everything it does not understand would report a tidy taxonomy that
 * quietly hides the failures nobody has looked at yet — and those are the
 * interesting ones.
 */
export const classify = (text: string | null | undefined): FailureShape => {
  if (!text || !text.trim()) {
    return { signature: UNCLASSIFIED, source: "agent", evidence: "(no output)" };
  }

  return (
    typescriptShape(text) ??
    bundleShape(text) ??
    // Before agentShape: a provider rejection also leaves files at 0, and
    // "wrote no files" would swallow the more specific cause.
    providerShape(text) ??
    agentShape(text) ?? {
      signature: UNCLASSIFIED,
      source: "agent",
      // Keep the tail: the summary line is at the end.
      // The tail, not the head: build tools print the failure summary last.
      evidence: sanitize(text.split("\n").slice(-3).join(" ")).slice(0, 300),
    }
  );
};

/** Every distinct shape in a set of failures, most frequent first. */
export const tally = (
  failures: ReadonlyArray<{ id: string; text: string | null }>,
): Array<{ shape: FailureShape; count: number; runIds: string[] }> => {
  const groups = new Map<
    string,
    { shape: FailureShape; count: number; runIds: string[] }
  >();

  for (const failure of failures) {
    const shape = classify(failure.text);
    const existing = groups.get(shape.signature);

    if (existing) {
      existing.count += 1;
      existing.runIds.push(failure.id);
    } else {
      groups.set(shape.signature, {
        shape,
        count: 1,
        runIds: [failure.id],
      });
    }
  }

  return [...groups.values()].sort((a, b) => b.count - a.count);
};
