"""Failure shapes, derived deterministically.

Port of ``src/lib/taxonomy.ts``.

NO EMBEDDINGS, NO CLUSTERING.

Compiler output is structured, so a signature can be extracted by
normalising away paths, line numbers, quoted identifiers and hashes — and
then **the signature is the identity**. The usual hard problem of
clustering, keeping shape ids stable as clusters split and merge across
runs, is designed out rather than solved.

Unclassified failures are never absorbed into a catch-all. A bucket that
swallows what it does not understand reports a tidy taxonomy and hides the
failures nobody has looked at.

THE BAR THIS FILE HAS TO CLEAR

The TypeScript implementation is deleted only once this one produces
identical signatures on the captured fixtures in ``evals/fixtures``. Same
inputs, same outputs, or the port is not a port.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

__all__ = [
    "FailureShape",
    "UNCLASSIFIED",
    "normalise",
    "sanitize",
    "classify",
    "tally",
]

UNCLASSIFIED = "unclassified"


@dataclass(frozen=True)
class FailureShape:
    #: Stable, human-readable identity. Never a hash — these get read.
    signature: str
    #: Which check produced it.
    source: str
    evidence: str


# Type errors that mean the harness is broken, not the generated code.
#
# These are indistinguishable from real type errors by exit code — a genuine
# non-zero from a genuine `tsc` diagnostic — so the infrastructure-fault
# guard cannot catch them. The only tell is *what* the error names.
#
# `LayoutProps` is generated by Next into `.next/types`. When the check copy
# lacked it, every project failed typecheck including "Hello world", and the
# baseline reported 0% across sixteen runs. Plausible, publishable, entirely
# about a missing directory.
_HARNESS_TYPE_ERRORS: list[tuple[re.Pattern[str], str]] = [
    (
        re.compile(r"Cannot find name '(LayoutProps|PageProps|RouteContext)'"),
        "Next generated types missing — run `next typegen` in the copy",
    ),
]

# Order matters: paths before line numbers, quoted strings before bare
# numbers, or the earlier rules eat text the later ones needed.
_PATH = re.compile(r"(?:\.{0,2}/)?[\w.-]+(?:/[\w.-]+)+\.\w+(?:\(\d+,\d+\))?")
_LOC = re.compile(r"\(\d+,\d+\)|:\d+:\d+")
_QUOTED = re.compile(r"'[^']*'|\"[^\"]*\"|`[^`]*`")
_HASH = re.compile(r"\b[0-9a-f]{8,}\b", re.IGNORECASE)
_NUMBER = re.compile(r"\b\d+\b")
_WHITESPACE = re.compile(r"\s+")
_CONTROL = re.compile(r"[\x00-\x1F\x7F]+")


def normalise(line: str) -> str:
    """Strip the parts that vary between two instances of the same failure."""
    out = line.strip()
    out = _PATH.sub("<path>", out)
    out = _LOC.sub("<loc>", out)
    out = _QUOTED.sub("<name>", out)
    out = _HASH.sub("<hash>", out)
    out = _NUMBER.sub("<n>", out)
    return _WHITESPACE.sub(" ", out).strip()


def sanitize(text: str) -> str:
    """Make captured output safe to print.

    Compiler output is raw bytes from another machine. On Windows every line
    ends ``\\r\\n``, and a lone ``\\r`` in the middle of a printed string
    returns the terminal cursor to column zero: whatever comes after
    overwrites what came before, on the same visual line.

    The symptom was reports appearing to drop rows. Nothing was dropped —
    the text was printed and then written over, which looks identical to a
    printer bug and is not one.
    """
    return _WHITESPACE.sub(" ", _CONTROL.sub(" ", text)).strip()


def _typescript_shape(text: str) -> FailureShape | None:
    """TypeScript diagnostics: ``error TS2322: Type 'x' is not assignable…``"""
    match = re.search(r"error (TS\d+):\s*([^\n]+)", text)
    if not match:
        return None

    code, message = match.group(1), match.group(2)

    # Named explicitly so a broken harness reads as a broken harness rather
    # than as a fleet of bad generations.
    for pattern, reason in _HARNESS_TYPE_ERRORS:
        if pattern.search(text):
            return FailureShape(
                signature=f"HARNESS: {reason}",
                source="typecheck",
                evidence=sanitize(match.group(0)),
            )

    return FailureShape(
        signature=f"{code}: {normalise(message)}",
        source="typecheck",
        evidence=sanitize(match.group(0)),
    )


# Next build failures, in the handful of forms it actually emits.
# Ordered most specific first: `Module not found` and `Failed to compile`
# often appear in the same output, and the first is the useful one.
@dataclass(frozen=True)
class _NextPattern:
    pattern: re.Pattern[str]
    label: str
    #: Group holding an identifier that varies case to case and must be
    #: redacted before the signature is built. See `_bundle_shape`.
    redact: int | None = None


_NEXT_PATTERNS: list[_NextPattern] = [
    _NextPattern(re.compile(r"Module not found:\s*([^\n]+)"), "Module not found"),
    # THE CODE COMPILED AND THEN THREW WHILE RENDERING.
    #
    # Next prerenders static pages during `next build`, so a component that
    # crashes on render fails the build with no compile error at all — the
    # output says `Compiled successfully` a few lines above.
    #
    # The only category where typecheck passes, the bundle compiles, and
    # the app is still broken. It sat in `unclassified` until someone read
    # it, which is that bucket working as designed.
    #
    # Captures the thrown error, not the page: the page name varies per
    # generation and the error is the cause. Unredacted, unlike
    # export-not-found — two different thrown errors are two different
    # bugs, where two missing exports from one package are one.
    _NextPattern(
        re.compile(r"Error occurred prerendering page[\s\S]*?\nError: ([^\n]+)"),
        "Prerender error",
    ),
    _NextPattern(
        re.compile(r"(You're importing a component that needs[^\n]+)"),
        "Server/client boundary",
    ),
    _NextPattern(re.compile(r"(Error: .*?use client[^\n]*)"), "Server/client boundary"),
    _NextPattern(re.compile(r"(ReferenceError: [^\n]+)"), "ReferenceError"),
    _NextPattern(re.compile(r"(SyntaxError: [^\n]+)"), "SyntaxError"),
    _NextPattern(re.compile(r"(TypeError: [^\n]+)"), "TypeError"),
    _NextPattern(
        re.compile(r"Export .* doesn't exist in target module"), "Bad export"
    ),
    # Turbopack's current phrasing for the same thing. KEPT SEPARATE FROM
    # `Cannot find module` ON PURPOSE — they look alike and mean opposite
    # things: module-not-found is the template's fault, export-not-found is
    # the agent inventing a name or the installed version dropping one.
    # Collapsing them would send every investigation to the wrong place.
    #
    # `redact=1` because the exported name is bare — not quoted — so
    # `normalise` leaves it alone. Without redaction `Github` and `Linkedin`
    # become two shapes for one cause, and a tally fragments into instances.
    # The TS2305 form of this same failure collapses to one shape because
    # tsc quotes the identifier; this one has to be told.
    _NextPattern(
        re.compile(r"The export (\S+) was not found in module"),
        "Export not found",
        redact=1,
    ),
    _NextPattern(re.compile(r"(Cannot find module [^\n]+)"), "Cannot find module"),
]


def _bundle_shape(text: str) -> FailureShape | None:
    for entry in _NEXT_PATTERNS:
        match = entry.pattern.search(text)
        if not match:
            continue

        if entry.redact is not None:
            # Redact inside the full match rather than using the captured
            # group: the surrounding words are what make the signature
            # readable, and the group is the only part that varies.
            detail = match.group(0).replace(match.group(entry.redact), "<name>")
        elif match.groups():
            detail = match.group(1)
        else:
            detail = match.group(0)

        return FailureShape(
            signature=f"{entry.label}: {normalise(detail)}",
            source="bundle",
            evidence=sanitize(match.group(0))[:300],
        )
    return None


def _provider_shape(text: str) -> FailureShape | None:
    """Model-provider rejections.

    Deliberately classified as agent failures, not infrastructure faults.

    A 429 is throttling and says nothing about the run. A 400 is different:
    the request was malformed or too large, and the most likely cause is the
    agent looping until it exhausted the context window. That is a real
    failure mode of the agent, and burying it in the infrastructure bucket
    would hide it.
    """
    if re.search(
        r"context.{0,20}(length|window)|too many tokens|maximum context",
        text,
        re.IGNORECASE,
    ):
        return FailureShape(
            signature="Provider rejected: context exhausted",
            source="agent",
            evidence=sanitize(text)[:300],
        )

    status = re.search(r"unsuccessful status code:?\s*(\d{3})", text, re.IGNORECASE)
    if status and status.group(1).startswith("4"):
        return FailureShape(
            # Kept distinct from the context case: same symptom, different
            # cause, and merging them would make the common one invisible.
            signature=f"Provider rejected request ({status.group(1)})",
            source="agent",
            evidence=sanitize(text)[:300],
        )

    if re.search(r"AIGatewayError|AI request failed", text, re.IGNORECASE):
        return FailureShape(
            signature="Provider request failed",
            source="agent",
            evidence=sanitize(text)[:300],
        )

    return None


# A refusal is not a failure to produce. See the TypeScript original for the
# full reasoning: `adversarial-01` is a prompt-injection attempt, the agent
# declined, and the harness scored the correct behaviour as a defect.
_REFUSAL = re.compile(
    r"\b(I (?:can(?:not|'t)|won't|will not|am not able to)|I'm not going to"
    r"|I need to decline|I have to decline)\b"
    r"|ignore (?:my|the|previous) instructions|system prompt",
    re.IGNORECASE,
)


def _agent_shape(text: str) -> FailureShape | None:
    if re.search(r"summary: false", text) and _REFUSAL.search(text):
        return FailureShape(
            signature="Agent declined the request",
            source="agent",
            evidence=sanitize(text)[-300:],
        )

    if re.search(r"summary: false", text):
        return FailureShape(
            signature="Agent produced no summary",
            source="agent",
            evidence="no <task_summary> emitted",
        )

    if re.search(r"files: 0", text):
        return FailureShape(
            signature="Agent wrote no files",
            source="agent",
            evidence="fileCount 0",
        )

    return None


def classify(text: str | None) -> FailureShape:
    """Derive the shape of a failure.

    Returns UNCLASSIFIED rather than guessing.
    """
    if not text or not text.strip():
        return FailureShape(UNCLASSIFIED, "agent", "(no output)")

    for rule in (_typescript_shape, _bundle_shape, _provider_shape, _agent_shape):
        # `_provider_shape` before `_agent_shape`: a provider rejection also
        # leaves files at 0, and "wrote no files" would swallow the more
        # specific cause.
        shape = rule(text)
        if shape:
            return shape

    return FailureShape(
        signature=UNCLASSIFIED,
        source="agent",
        # The tail, not the head: build tools print the failure summary last.
        evidence=sanitize(" ".join(text.split("\n")[-3:]))[:300],
    )


@dataclass
class ShapeGroup:
    shape: FailureShape
    count: int
    run_ids: list[str] = field(default_factory=list)


def tally(failures: list[tuple[str, str | None]]) -> list[ShapeGroup]:
    """Every distinct shape in a set of failures, most frequent first.

    Takes ``(run_id, text)`` pairs.
    """
    groups: dict[str, ShapeGroup] = {}

    for run_id, text in failures:
        shape = classify(text)
        existing = groups.get(shape.signature)

        if existing:
            existing.count += 1
            existing.run_ids.append(run_id)
        else:
            groups[shape.signature] = ShapeGroup(shape, 1, [run_id])

    return sorted(groups.values(), key=lambda g: g.count, reverse=True)
